import os
import time

print ('H/')
time.sleep(0.5)
os.system('clear')
print ('H|')
time.sleep(0.5)
os.system('clear')
print ('HA/')
time.sleep(0.5)
os.system('clear')
print ('HA|')
time.sleep(0.5)
os.system('clear')
print ('HAR/')
time.sleep(0.5)
os.system('clear')
print ('HAR|')
time.sleep(0.5)
os.system('clear')
print ('HARI/')
time.sleep(0.5)
os.system('clear')
print ('HARI|')
time.sleep(0.5)
os.system('clear')
print ('HARIS/')
time.sleep(0.5)
os.system('clear')
print ('HARIS|')
time.sleep(0.5)
os.system('clear')
print ('HARIS /')
time.sleep(0.5)
os.system('clear')
print ('HARIS G|')
time.sleep(0.5)
os.system('clear')
print ('HARIS G/')
time.sleep(0.5)
os.system('clear')
print ('HARIS GI|')
time.sleep(0.5)
os.system('clear')
print ('HARIS GI/')
time.sleep(0.5)
os.system('clear')
print ('HARIS GIT|')
time.sleep(0.5)
os.system('clear')
print ('HARIS GIT/')
time.sleep(0.5)
os.system('clear')
print ('HARIS GITA|')
time.sleep(0.5)
os.system('clear')
print ('HARIS GITA/')
time.sleep(0.5)
os.system('clear')
print ('HARIS GITAM|')
time.sleep(0.5)
os.system('clear')
print ('HARIS GITAM/')
time.sleep(0.5)
os.system('clear')
print ('HARIS GITAMA|')
time.sleep(0.5)
os.system('clear')
print ('HARIS GITAMA/')
time.sleep(0.5)
os.system('clear')
print ('HARIS GITAMA')
time.sleep(0.5)